WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
DEBUG:asyncio:Using proactor: IocpProactor
INFO:django.utils.autoreload:D:\Web app\babaco\shop\models.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:D:\Web app\babaco\store\views.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
INFO:django.utils.autoreload:D:\Web app\babaco\store\views.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
ERROR:django.request:Internal Server Error: /store/
Traceback (most recent call last):
  File "D:\Web app\django\lib\site-packages\django\db\models\fields\__init__.py", line 1774, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'method'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Web app\django\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Web app\django\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Web app\babaco\store\views.py", line 13, in home
    products = Product.objects.filter(store_id=req.session.get)
  File "D:\Web app\django\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Web app\django\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Web app\django\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "D:\Web app\django\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\Web app\django\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Web app\django\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\Web app\django\lib\site-packages\django\db\models\sql\query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "D:\Web app\django\lib\site-packages\django\db\models\sql\query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "D:\Web app\django\lib\site-packages\django\db\models\lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "D:\Web app\django\lib\site-packages\django\db\models\fields\related_lookups.py", line 117, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "D:\Web app\django\lib\site-packages\django\db\models\fields\__init__.py", line 1776, in get_prep_value
    raise e.__class__(
TypeError: Field 'user_id' expected a number but got <bound method SessionBase.get of <django.contrib.sessions.backends.db.SessionStore object at 0x000001B9C7708880>>.
INFO:django.utils.autoreload:D:\Web app\babaco\store\views.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
INFO:django.utils.autoreload:D:\Web app\babaco\store\views.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
ERROR:django.request:Internal Server Error: /store/
Traceback (most recent call last):
  File "D:\Web app\django\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Web app\django\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Web app\babaco\store\views.py", line 13, in home
    store = Store.objects.get(id=req.session.get('store_id'))
  File "D:\Web app\django\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Web app\django\lib\site-packages\django\db\models\query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "D:\Web app\django\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Web app\django\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "D:\Web app\django\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\Web app\django\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Web app\django\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\Web app\django\lib\site-packages\django\db\models\sql\query.py", line 1258, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "D:\Web app\django\lib\site-packages\django\db\models\sql\query.py", line 1084, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\Web app\django\lib\site-packages\django\db\models\sql\query.py", line 1481, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'id' into field. Choices are: contact, email, location, name, order, password, product, review, user_id
INFO:django.utils.autoreload:D:\Web app\babaco\store\views.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
INFO:django.utils.autoreload:D:\Web app\babaco\store\views.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
INFO:django.utils.autoreload:D:\Web app\babaco\store\views.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
ERROR:django.request:Internal Server Error: /store/
Traceback (most recent call last):
  File "D:\Web app\django\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Web app\django\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Web app\babaco\store\views.py", line 16, in home
    return render(req, 'store/home.html', context)
  File "D:\Web app\django\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Web app\django\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Web app\django\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Web app\django\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Web app\django\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Web app\django\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Web app\django\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Web app\django\lib\site-packages\django\template\loader_tags.py", line 270, in do_extends
    nodelist = parser.parse()
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Web app\django\lib\site-packages\django\template\loader_tags.py", line 213, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '/home.html' from 'store/home.html'
ERROR:django.request:Internal Server Error: /store/
Traceback (most recent call last):
  File "D:\Web app\django\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Web app\django\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Web app\babaco\store\views.py", line 16, in home
    return render(req, 'store/home.html', context)
  File "D:\Web app\django\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Web app\django\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Web app\django\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Web app\django\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Web app\django\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Web app\django\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Web app\django\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Web app\django\lib\site-packages\django\template\loader_tags.py", line 270, in do_extends
    nodelist = parser.parse()
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Web app\django\lib\site-packages\django\template\loader_tags.py", line 213, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' user/home_user.css' from 'static user/home_user.css'
ERROR:django.request:Internal Server Error: /store/
Traceback (most recent call last):
  File "D:\Web app\django\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Web app\django\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Web app\babaco\store\views.py", line 16, in home
    return render(req, 'store/home.html', context)
  File "D:\Web app\django\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Web app\django\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Web app\django\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Web app\django\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Web app\django\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Web app\django\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Web app\django\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Web app\django\lib\site-packages\django\template\loader_tags.py", line 270, in do_extends
    nodelist = parser.parse()
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Web app\django\lib\site-packages\django\template\loader_tags.py", line 213, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' user/home_user.css' from 'static user/home_user.css'
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /store/
Traceback (most recent call last):
  File "D:\Web app\django\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Web app\django\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Web app\babaco\store\views.py", line 16, in home
    return render(req, 'store/home.html', context)
  File "D:\Web app\django\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Web app\django\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Web app\django\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Web app\django\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Web app\django\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Web app\django\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Web app\django\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Web app\django\lib\site-packages\django\template\loader_tags.py", line 270, in do_extends
    nodelist = parser.parse()
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Web app\django\lib\site-packages\django\template\loader_tags.py", line 213, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' user/home_user.css' from 'static user/home_user.css'
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /store/
Traceback (most recent call last):
  File "D:\Web app\django\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Web app\django\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Web app\babaco\store\views.py", line 16, in home
    return render(req, 'store/home.html', context)
  File "D:\Web app\django\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Web app\django\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Web app\django\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Web app\django\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Web app\django\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Web app\django\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Web app\django\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Web app\django\lib\site-packages\django\template\loader_tags.py", line 270, in do_extends
    nodelist = parser.parse()
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Web app\django\lib\site-packages\django\template\loader_tags.py", line 213, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\Web app\django\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' 'user/home_user.css'' from 'static 'user/home_user.css''
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /profile/login/
WARNING:django.request:Not Found: /profile/login/
WARNING:django.request:Not Found: /profile/login/
WARNING:django.request:Not Found: /profile/login/
INFO:django.utils.autoreload:D:\Web app\babaco\store\views.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
INFO:django.utils.autoreload:D:\Web app\babaco\user\urls.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
INFO:django.utils.autoreload:D:\Web app\babaco\user\urls.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
INFO:django.utils.autoreload:D:\Web app\babaco\store\views.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
WARNING:django.request:Not Found: /store/product_pics/laptop.png
WARNING:django.request:Not Found: /store/product_pics/0038136-vivo-s1-pro-black8gb-ram-128gb-storage-250.jpg
WARNING:django.request:Not Found: /store/product_pics/Vivo-Apex-PNG-Image-1024x1024.png
WARNING:django.request:Not Found: /store/product_pics/microwave-oven.png
WARNING:django.request:Not Found: /store/product_pics/laptop.png
WARNING:django.request:Not Found: /store/product_pics/0038136-vivo-s1-pro-black8gb-ram-128gb-storage-250.jpg
WARNING:django.request:Not Found: /store/product_pics/microwave-oven.png
WARNING:django.request:Not Found: /store/product_pics/Vivo-Apex-PNG-Image-1024x1024.png
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /store/product_pics/laptop.png
WARNING:django.request:Not Found: /store/product_pics/0038136-vivo-s1-pro-black8gb-ram-128gb-storage-250.jpg
WARNING:django.request:Not Found: /store/product_pics/microwave-oven.png
WARNING:django.request:Not Found: /store/product_pics/Vivo-Apex-PNG-Image-1024x1024.png
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /store/product_pics/laptop.png
WARNING:django.request:Not Found: /store/product_pics/0038136-vivo-s1-pro-black8gb-ram-128gb-storage-250.jpg
WARNING:django.request:Not Found: /store/product_pics/microwave-oven.png
WARNING:django.request:Not Found: /store/product_pics/Vivo-Apex-PNG-Image-1024x1024.png
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:D:\Web app\babaco\store\views.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
WARNING:django.request:Not Found: /store/product_pics/laptop.png
WARNING:django.request:Not Found: /store/product_pics/0038136-vivo-s1-pro-black8gb-ram-128gb-storage-250.jpg
WARNING:django.request:Not Found: /store/product_pics/Vivo-Apex-PNG-Image-1024x1024.png
WARNING:django.request:Not Found: /store/product_pics/microwave-oven.png
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:D:\Web app\babaco\store\views.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /profile/login/
WARNING:django.request:Not Found: /profile/login/
WARNING:django.request:Not Found: /profile/login/
WARNING:django.request:Not Found: /profile/login/
WARNING:django.request:Not Found: /profile/login/
WARNING:django.request:Not Found: /profile/login/
INFO:django.utils.autoreload:D:\Web app\babaco\user\views.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
INFO:django.utils.autoreload:D:\Web app\babaco\store\urls.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
